import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
	variable: "--font-plus-jakarta-sans",
	subsets: ["latin", "latin-ext"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "weart.hu",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="hu">
			<body className={`${plusJakartaSans.className} antialiased`}>{children}</body>
		</html>
	);
}
